### ISSUE TITLE
update dependencies, http: ^1.0.0 is not supported

### ISSUE THREAD

**Issue by MominRaza** [petehouston/flutter-emoji#22]
[yourapp] flutter pub get
Resolving dependencies...
Because flutter_emoji 2.4.0 depends on http ^0.13.4 and no versions of flutter_emoji match >2.4.0 <3.0.0, flutter_emoji ^2.4.0 requires http ^0.13.4.
So, because yourapp depends on both flutter_emoji ^2.4.0 and http ^1.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on http: flutter pub add http:^0.13.6
exit code 1

**Comment by petehouston** [comment]
thanks, I'll take a look at in a few days.

**Comment by chimura** [comment]
I have the same issue. http outdated version is a deal-breaker for projects that uses other packages that depend on newer versions of http - and there's a lot of important packages that needs http ^1.0.0 (like facebook integration package)

**Comment by petehouston** [comment]
thanks, it's updated to `2.5.0` with new new `http` and `sdk` version constraints.
