### ISSUE TITLE
Substitute dash with underscore in JSON_EMOJI string

### ISSUE THREAD

**Issue by melvinm99** [petehouston/flutter-emoji#5]
Hi, thanks for your work. I noticed that emoji with a tone (like "skin-tone-2" for example) can't be parsed because dashed don't get matched in your emojify method. I solved by replacing every dash with an underscore in the JSON_EMOJI string field. 
Hope that helps!

**Comment by petehouston** [comment]
It is fixed in [2.2.0](https://github.com/petehouston/flutter-emoji/releases/tag/2.2.0). Thank you :)
