### ISSUE TITLE
Can this library display emojis the phone does not have? 

### ISSUE THREAD

**Issue by febg11** [petehouston/flutter-emoji#7]
If an iphone on an older version is being used.. Can this library display emojis that it does not have?

**Comment by mursalov** [comment]
@febg11 Have you found an answer to this?

**Comment by daniel-hopkins** [comment]
Does not seem to. That was my hope when installing it, but I tested on some older devices using browserstack and I still see the missing emoji icon.
Hopefully I'm wrong.

**Comment by petehouston** [comment]
Added more emojis in Unicode 13.0 since v2.3.3+.
