### ISSUE TITLE
App crashes when I install the package

### ISSUE THREAD

**Issue by GENL** [petehouston/flutter-emoji#9]
The flutter app crashes after I install flutter-emoji and import it above the current displayed view, each time I run hot-reload the app. It does the same when I use Emoji picker package. Is a problem with my flutter version?

`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [version 10.0.18362.592], locale en-EN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.39.2)
[√] Connected device (1 available)

• No issues found!`

**Comment by GENL** [comment]
I've migrated to the beta version of flutter and it works right now.

**Comment by petehouston** [comment]
Strange, let me take a look at your version.

**Comment by petehouston** [comment]
@GENL It works fine for me, tested on both Android and iOS. You might want to re-install Flutter, I think.

**Comment by GENL** [comment]
I have tested with different versions of flutter and the problem persists. Have you tried to hot-relad the page 3 or 4 times?

**Comment by petehouston** [comment]
Yes, I did, tried several different versions. It works fine. What is your device name and model?

**Comment by GENL** [comment]
It is a Sumsung Galaxy S5
Model: SM-G900T1

**Comment by petehouston** [comment]
I haven't been able to figure out it yet. Could you get a debug log via adb?
